Alert
shinonome-inc/kogaokumura-frontend-basic-2022-todoapp pull request #11
Opened 2023-01-15 04:00 UTC by kogaokumura

2023-01-15 17:57 UTC, KEISUKE0293 reviewed
アラートの実装自体はできているので大丈夫ですが。

- アラートの表示位置がfigmaとずれている
- レスポンシブ対応していない？（モバイルサイズ対応できていない）
- EditButtonのみhover時のcursorが変化しない

といった点が気になりました。
もし余裕があればこういったところも是非直していければいいかなと思います！

2023-01-17 15:31 UTC, Higashiji requested changes
基本的には問題ありません！
クオリティ向上のため二点確認お願いします！

---
![image](https://user-images.githubusercontent.com/83479175/212939767-c2d764d9-73ce-4bd9-bf53-c8a30a8500b4.png)
おそらくどこかで横幅を固定値で持っているため、横幅が狭い時にうまく表示されていません。
横幅が画面幅を超えると横スクロールが発生してしまうため、これを避けるために `max-width` などを使って画面幅を超えないようにしてみてください。

---
https://user-images.githubusercontent.com/83479175/212940196-f7086dd4-0a42-47cf-b8d1-5e7a45fd9722.mov

ロードした際に最後のタスクに focus されてしまっています。これはおそらく `organisms/task` で defaultIsEditingが常にtrueであることに由来しています。
一度編集が完了したタスクは、マウント時にフォーカスが当たらないようにしてみましょう。

2023-01-19 04:20 UTC, higashiji2000 approved these changes
LGTM 🎉

2023-01-19 04:20 UTC, merged

2023-02-06 08:57 UTC, kogaokumura commented
![image](https://user-images.githubusercontent.com/107789098/216928101-9e514670-60c8-4397-bc0a-6b538eb6a904.png)

2023-02-06 08:57 UTC, kogaokumura commented
あいうえお
![image](https://user-images.githubusercontent.com/107789098/216928199-888f7f74-f2cc-4a4c-9478-d51edebf7e87.png)