Organisms todocard
shinonome-inc/kogaokumura-frontend-basic-2022-todoapp pull request #7
Opened 2022-12-08 07:41 UTC by kogaokumura

2022-12-11 17:04 UTC, Hasegawa62 reviewed
すみません、TODO/DONEの挙動を理解できていない(解決方法がわかっていない)状態の発言なので詳しく指摘できないのですが...
とりあえず問題点として
・タスクが何も追加されていないときのスタイルが手本と異なる
・チェックボックスによるタスクの削除ができない
があります。
この2点もう一度検討してみてください。

2022-12-14 06:24 UTC, higashiji2000 requested changes
見た目がfigmaと違うので、修正をお願いします。
inputが横幅いっぱいに広がるようになっていてほしいのと、Organismsの段階では width を設定しなくても大丈夫です。

---

動作としては問題ないので、見た目だけ修正お願いします 🙏 
また、差分が多くなっているので
```
git pull origin master
```
で最新のmasterをマージしたのちpushをお願いします。ｚ

2022-12-14 06:24 UTC, Higashiji commented on src/components/Organisms/TodoCard/index.jsx
> +  width: 500px;
この段階では width は横幅いっぱいに広がるので大丈夫です。

2022-12-14 06:24 UTC, Higashiji commented on src/components/Organisms/TodoCard/index.jsx
> +    if (state == "TODO") {
```suggestion
    if (state === "TODO") {
```
基本的に厳密比較を使うようにしてください。

2022-12-14 06:24 UTC, Higashiji commented on src/components/Organisms/TodoCard/index.jsx
> +            let editedTask = [...task];
```suggestion
            const editedTask = [...task];
```
constで宣言された変数への再宣言、再代入は不可能ですが、プロパティの編集は可能です。
そのため、今回の処理であればconstで大丈夫です。
基本的に let より const の方が望ましいということを意識できるとグッドだと思います！
（些細な点なので、今回は直さなくても大丈夫です。）

2022-12-14 06:27 UTC, higashiji2000 reviewed
<img width="541" alt="image" src="https://user-images.githubusercontent.com/83479175/207522365-6ef5b209-c274-4455-9c8c-1a36009841ed.png">
ここのmarginのせいで下方向の余白が広くなってしまっているようです。

2022-12-17 06:22 UTC, merged