Peges mainpage
shinonome-inc/kogaokumura-frontend-basic-2022-todoapp pull request #8
Opened 2022-12-14 13:09 UTC by kogaokumura

2022-12-18 18:52 UTC, KEISUKE0293 reviewed
Todoカードとしての機能は問題ないと思います。
ただ、figmaと比べても所々にサイズや余白の大きさが異なる部分があるのでそこを修正してほしいです！

2022-12-19 14:08 UTC, Hasegawa62 commented
タスクがないときに無駄な余白ができてしまうのが気になります。
以下のサイト、参考になると思うので修正お願いします！
https://open8tech.hatenablog.com/entry/2019/01/25/113916
![image](https://user-images.githubusercontent.com/94204610/208443603-8e1830f9-22ce-444c-880e-e40cf198e4d8.png)

2022-12-20 12:13 UTC, haruchu commented
以下の課題ページにも例があると思うのですが、タスクが空の時のデザインが例と異なります。
http://shinonome.io/frontend-basic-2022-textbook/pages-mainpage
<img width="803" alt="スクリーンショット 2022-12-20 21 12 33" src="https://user-images.githubusercontent.com/66406382/208664500-26e04d08-6d4e-4e10-83f8-a2dae8c1baad.png">
<img width="531" alt="スクリーンショット 2022-12-20 21 12 50" src="https://user-images.githubusercontent.com/66406382/208664544-7b981e8b-1048-4eb1-9f4d-8d3ee1bf69a9.png">

2022-12-23 13:50 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/209346314-8ef03d84-7f1b-498a-9693-399205bdb13e.png)
おそらく Atoms/input の幅が固定値になっているので、親要素の幅いっぱいに広がるように修正するとお手本に近づくと思います！

---

また、ToDoCardのDiffがPRに出てしまっています。
このブランチで `git pull origin master` していただくとToDoCardマージ済みのmasterがプルでき、差分がすっきりすることと思うので試してみてください。

2022-12-23 13:50 UTC, higashiji2000 commented on src/components/Atoms/Title/index.jsx
> +import React, { useState, useEffect } from "react";
特に意図はないと思いますがこのimportは不要そうですね

2022-12-24 13:19 UTC, kogaokumura commented
> 

atoms/inputのwidthを消してみたのですが、親要素の幅いっぱいに広がらないです。何か原因があるのでしょうか？

2022-12-24 14:50 UTC, higashiji2000 commented
https://github.com/shinonome-inc/kogaokumura-frontend-basic-2022-todoapp/blob/a1d686eb08e7a7cc3bdd79d040a3555aacec5c15/src/components/Molecules/Task/index.jsx#L46
おそらくTaskのところで幅を固定値で持ってしまっているのが原因なので、確認お願いします。
こんな感じで、widthの設定を解除し、その親でflex: 1; によって伸びるようにしたらいい感じになりました！↓
![image](https://user-images.githubusercontent.com/83479175/209441078-59a97133-085d-488e-9c60-12a354030606.png)

2022-12-25 04:24 UTC, kogaokumura commented
> https://github.com/shinonome-inc/kogaokumura-frontend-basic-2022-todoapp/blob/a1d686eb08e7a7cc3bdd79d040a3555aacec5c15/src/components/Molecules/Task/index.jsx#L46
> 
> 
> おそらくTaskのところで幅を固定値で持ってしまっているのが原因なので、確認お願いします。
> こんな感じで、widthの設定を解除し、その親でflex: 1; によって伸びるようにしたらいい感じになりました！↓
> ![image](https://user-images.githubusercontent.com/83479175/209441078-59a97133-085d-488e-9c60-12a354030606.png)

ありがとうございます！

2022-12-25 08:48 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/209462058-58424811-86ea-4d17-aa96-aa2dc602276c.png)
まだinputの幅が小さいままなので、ここだけ修正お願いします！
他は完璧だと思います。

2022-12-25 10:20 UTC, higashiji2000 approved these changes
LGTM 🌈

2022-12-25 12:06 UTC, merged